# Generated by Django 5.1.3 on 2024-11-05 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constutionapp', '0002_chapter_alter_article_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='section',
            new_name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='constutionapp.section'),
        ),
    ]
